print("Hello world")
X = input("What is your name? ")
print(X+"is my name");
Y = int(input())
Z = int(input())
print(Y)
print(X)
print("HiIII")
print("Hello")
print("editted by preethi hehehe")